export const studentsAssignments = [
    { id: 1, name: "Itay Yaffe", email: "itayy@codevalue.net", group: "A", submissionTime: new Date(), status: "Submission", grade: 83, progressValue: 92, isCheated: false, budget: 150, consumed: 32 },
    { id: 2, name: "Amichai Vaknin", email: "Amichai@codevalue.net", group: "B", submissionTime: new Date(), status: "Flegged", grade: 78, progressValue: 80, isCheated: true, budget: 150, consumed: 120 },
    { id: 3, name: "Alex Pshul", email: "Alex@codevalue.net", group: "D", submissionTime: new Date(), status: "Pending", grade: 98, progressValue: 47, isCheated: false, budget: 150, consumed: 88.93 },
    { id: 4, name: "Yarin Mansour", email: "Yarin@codevalue.net", group: "C", submissionTime: new Date(), status: "On Going", grade: 76, progressValue: 75, isCheated: false, budget: 150, consumed: 56 },
    { id: 5, name: "Suzan Zaher", email: "Suzan@codevalue.net", group: "A", submissionTime: new Date(), status: "Submission", grade: 93, progressValue: 85, isCheated: false, budget: 150, consumed: 17 },
    { id: 6, name: "Moti Hadash", email: "Moti@codevalue.net", group: "C", submissionTime: new Date(), status: "Submission", grade: 60, progressValue: 39, isCheated: true, budget: 150, consumed: 111 },
    { id: 7, name: "Amir Segal", email: "Amir@codevalue.net", group: "A", submissionTime: new Date(), status: "Flegged", grade: 55, progressValue: 45, isCheated: false, budget: 150, consumed: 100 },
    { id: 8, name: "Benny Reznik", email: "Benny@codevalue.net", group: "B", submissionTime: new Date(), status: "Submission", grade: 88, progressValue: 76, isCheated: false, budget: 150, consumed: 50 },
    { id: 9, name: "Idan Malka", email: "Idan@codevalue.net", group: "A", submissionTime: new Date(), status: "Submission", grade: 74, progressValue: 84, isCheated: false, budget: 150, consumed: 90 },
    { id: 10, name: "Aviv Shalom", email: "Aviv@codevalue.net", group: "D", submissionTime: new Date(), status: "On Going", grade: 91, progressValue: 80, isCheated: true, budget: 150, consumed: 65 },
    { id: 11, name: "Avi Ron", email: "Avi@codevalue.net", group: "A", submissionTime: new Date(), status: "Submission", grade: 80, progressValue: 100, isCheated: false, budget: 150, consumed: 88 },
    { id: 12, name: "Shoola Mokshim", email: "Shoola@codevalue.net", group: "A", submissionTime: new Date(), status: "Submission", grade: 55, progressValue: 92, isCheated: false, budget: 150, consumed: 65.46 },
    { id: 13, name: "Ran Yaakov", email: "Ran@codevalue.net", submissionTime: new Date(), status: "Submission", grade: 66, progressValue: 30, isCheated: false, budget: 150, consumed: 150 },
    { id: 14, name: "Dror Lavi", email: "Dror@codevalue.net", group: "B", submissionTime: new Date(), status: "Flegged", grade: 61, progressValue: 43, isCheated: false, budget: 150, consumed: 90 },
    { id: 15, name: "Alon Fliss", email: "Alon@codevalue.net", submissionTime: new Date(), status: "Pending", grade: 96, progressValue: 92, isCheated: true, budget: 150, consumed: 88 },
    { id: 16, name: "Libi Hadad", email: "Libi@codevalue.net", group: "C", submissionTime: new Date(), status: "On Going", grade: 69, progressValue: 69, isCheated: false, budget: 150, consumed: 123 },
    { id: 17, name: "Ben Hornado", email: "Ben@codevalue.net", group: "A", submissionTime: new Date(), status: "Flegged", grade: 100, progressValue: 0, isCheated: true, budget: 150, consumed: 43 },
    { id: 18, name: "Danny Kaplunsky", email: "Danny@codevalue.net", group: "D", submissionTime: new Date(), status: "Submission", grade: 93, progressValue: 66, isCheated: false, budget: 150, consumed: 145 },
    { id: 19, name: "We Sum", email: "We@codevalue.net", submissionTime: new Date(), status: "Pending", grade: 83, progressValue: 50, isCheated: false, budget: 150, consumed: 49 },

]